# Generated by Django 4.2.1 on 2024-07-17 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comuna',
            fields=[
                ('id_comuna', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_comuna', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('rut_empresa', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_emp', models.CharField(max_length=20)),
                ('ubicacion', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Pagina',
            fields=[
                ('id_pagina', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('nombre_pagina', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maravillosas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=30)),
                ('precio', models.IntegerField()),
                ('descripcion', models.CharField(max_length=100)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre_region', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maravillosas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('nombre_usuario', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, max_length=20, null=True)),
                ('apellido', models.CharField(blank=True, max_length=20, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=15)),
                ('direccion', models.CharField(max_length=50)),
                ('comuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maravillosas.comuna')),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maravillosas.pagina')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maravillosas.region')),
            ],
        ),
        migrations.AddField(
            model_name='comuna',
            name='empresa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maravillosas.empresa'),
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id_carrito', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('pagina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maravillosas.pagina')),
            ],
        ),
    ]
